#!/usr/bin/env python
"""
This module provides business object class to interact with datatiers table. 
"""

__revision__ = "$Id: DBSDataTier.py,v 1.2 2010/05/03 20:21:09 afaq Exp $"
__version__ = "$Revision: 1.2 $"

from WMCore.DAOFactory import DAOFactory
import memcache

class DBSDataTier:
    """
    DataTier business object class
    """
    def __init__(self, logger, dbi, owner):
	daofactory = DAOFactory(package='dbs.dao', logger=logger, dbinterface=dbi, owner=owner)
	self.logger = logger
	self.dbi = dbi
	self.owner = owner

	self.sm = daofactory(classname="SequenceManager")
	self.dataTier = daofactory(classname="DataTier.List")
	self.dtin = daofactory(classname="DataTier.Insert")

    def listDataTiers(self, data_tier_name=""):
	"""
	List data tier(s)
	"""
	try:
	    cache=memcache.Client(["cmssrv49.fnal.gov:11212"])
	    conn = self.dbi.connection()
	    result = self.dataTier.execute(conn, data_tier_name, cache=cache)
	    return result
	except Exception, ex:
	    raise ex
	finally:
	    conn.close()

    def insertDataTier(self, businput):
        """
        Input dictionary has to have the following keys:
        data_tier_name, creation_date, create_by
        it builds the correct dictionary for dao input and executes the dao
        """
	conn = self.dbi.connection()
        tran = conn.begin()
	cache=memcache.Client(["cmssrv49.fnal.gov:11212"])
        try:
	    businput["data_tier_id"] = self.sm.increment(conn, "SEQ_DT", tran)
	    assert businput["data_tier_name"]
	    assert businput["creation_date"]
	    assert businput["create_by"]
            self.dtin.execute(conn, businput, tran, cache)
            tran.commit()
        except Exception, ex:
                if str(ex).lower().find("unique constraint") != -1 or str(ex).lower().find("duplicate") != -1:
                        # already exist
                        self.logger.warning("Unique constraint violation being ignored...")
                        self.logger.warning("%s" % ex)
			pass
		else:
            		tran.rollback()
            		self.logger.exception(ex)
            		raise
        finally:
            conn.close()

